language: java
jdk: openjdk8

jobs:
  include:
    - script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    - script: "mvn test -B"
    - stage: deploy
      deploy:
        provider: script
        script: "cp settings.xml $HOME/.m2/settings.xml && mvn deploy"
        skip_cleanup: true

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
