language: java
jdk: openjdk8

jobs:
  include:
    - stage: test
    - stage: deploy
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
        - echo $GPG_PASSPHRASE
      install: skip
      script: skip
      deploy:
        provider: script
        script: "cp settings.xml $HOME/.m2/settings.xml && mvn deploy -Pdeploy"
        skip_cleanup: true

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
