language: java
jdk: openjdk8

jobs:
  include:
    - stage: test
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: "cp settings.xml $HOME/.m2/settings.xml && mvn deploy"
        skip_cleanup: true

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
